In [43]:
import torch

In [44]:
def printTensorInfo(tensor, title):
    print(f"====={title}=====")
    print(f"tensor:\n{tensor}")
    print(f"shape: {tensor.shape}")
    print(f"dtype: {tensor.dtype}")
    print(f"type: {tensor.type()}")
    print(f"dim: {tensor.dim()}")


In [45]:
# Различные способы создания тензоров
tensorRecommended = torch.Tensor(3, 5, 2)
printTensorInfo(tensorRecommended, "tensorRecommended")
tensorNotRecommended = torch.empty(3, 5, 2)
printTensorInfo(tensorNotRecommended, "tensorNotRecommended")
tensorZeros = torch.zeros(3, 5, 2)
printTensorInfo(tensorZeros, "tensorZeros")
tensorOnes = torch.ones(3, 5, 2)
printTensorInfo(tensorOnes, "tensorOnes")
tensorRand = torch.rand(3, 5, 2)
printTensorInfo(tensorRand, "tensorRand")
tensorSpecificDtype = torch.empty(3, 5, 2, dtype=torch.uint8)
printTensorInfo(tensorSpecificDtype, "tensorSpecificDtype")
tensorClass = torch.IntTensor(3, 5, 2)
printTensorInfo(tensorClass, "tensorClass")

=====tensorRecommended=====
tensor:
tensor([[[-1.5974e+29,  1.7516e-42],
         [ 1.0000e+00,  1.0000e+00],
         [ 1.0000e+00,  1.0000e+00],
         [ 1.0000e+00,  1.0000e+00],
         [ 1.0000e+00,  1.0000e+00]],

        [[ 1.0000e+00,  1.0000e+00],
         [ 1.0000e+00,  1.0000e+00],
         [ 1.0000e+00,  1.0000e+00],
         [ 1.0000e+00,  1.0000e+00],
         [ 1.0000e+00,  1.0000e+00]],

        [[ 1.0000e+00,  1.0000e+00],
         [ 1.0000e+00,  1.0000e+00],
         [ 1.0000e+00,  1.0000e+00],
         [ 1.0000e+00,  1.0000e+00],
         [ 1.0000e+00,  1.0000e+00]]])
shape: torch.Size([3, 5, 2])
dtype: torch.float32
type: torch.FloatTensor
dim: 3
=====tensorNotRecommended=====
tensor:
tensor([[[-1.5972e+29,  1.7516e-42],
         [ 7.6972e-02,  3.1718e-01],
         [ 8.8820e-01,  4.0879e-01],
         [ 8.5357e-01,  2.8432e-01],
         [ 6.1513e-01,  1.6174e-01]],

        [[ 5.6949e-01,  1.4202e-01],
         [ 2.6689e-02,  4.2994e-01],
         [ 1.6297e-01,

In [46]:
# Различные способы создания тензоров с разными значениями
firstTensor = torch.tensor([1])
printTensorInfo(firstTensor, "firstTensor")
secondTensor = torch.tensor([1, 2.0])
printTensorInfo(secondTensor, "secondTensor")
thirdTensor = torch.tensor([[1, 2], [3, 4], [5, 6]])
printTensorInfo(thirdTensor, "thirdTensor")
fourthTensor = torch.tensor([[1, 2], [3, 4], [5, 6]], dtype=torch.float32)
printTensorInfo(fourthTensor, "fourthTensor")

=====firstTensor=====
tensor:
tensor([1])
shape: torch.Size([1])
dtype: torch.int64
type: torch.LongTensor
dim: 1
=====secondTensor=====
tensor:
tensor([1., 2.])
shape: torch.Size([2])
dtype: torch.float32
type: torch.FloatTensor
dim: 1
=====thirdTensor=====
tensor:
tensor([[1, 2],
        [3, 4],
        [5, 6]])
shape: torch.Size([3, 2])
dtype: torch.int64
type: torch.LongTensor
dim: 2
=====fourthTensor=====
tensor:
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
shape: torch.Size([3, 2])
dtype: torch.float32
type: torch.FloatTensor
dim: 2


In [47]:
# Еще способы заполнить тензор
tensorEye = torch.eye(3)
printTensorInfo(tensorEye, "tensorEye")
tensorFull = torch.full((2, 4), 5)
printTensorInfo(tensorFull, "tensorFull")
tensorArange = torch.arange(-5, 0, 2)
printTensorInfo(tensorArange, "tensorArange")
tensorFull.fill_(4) # Только inplace
printTensorInfo(tensorFull, "tensorFull")

=====tensorEye=====
tensor:
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
shape: torch.Size([3, 3])
dtype: torch.float32
type: torch.FloatTensor
dim: 2
=====tensorFull=====
tensor:
tensor([[5, 5, 5, 5],
        [5, 5, 5, 5]])
shape: torch.Size([2, 4])
dtype: torch.int64
type: torch.LongTensor
dim: 2
=====tensorArange=====
tensor:
tensor([-5, -3, -1])
shape: torch.Size([3])
dtype: torch.int64
type: torch.LongTensor
dim: 1
=====tensorFull=====
tensor:
tensor([[4, 4, 4, 4],
        [4, 4, 4, 4]])
shape: torch.Size([2, 4])
dtype: torch.int64
type: torch.LongTensor
dim: 2


In [48]:
# Методы преобразования формы тензоров
exampleTensor = torch.arange(27)
printTensorInfo(exampleTensor, "exampleTensor")
view = exampleTensor.view((3, 9))
printTensorInfo(view, "view")
view2 = exampleTensor.view((3, 3, 3))
printTensorInfo(view2, "view2")
reshape = exampleTensor.reshape(3, 3, 3)
printTensorInfo(reshape, "reshape")

resize = exampleTensor.resize_((2, 3))
exampleTensor[0, 0] = 777
printTensorInfo(resize, "resize")

ravel = exampleTensor.ravel()
printTensorInfo(ravel, "ravel")
exampleTensorT = exampleTensor.permute(1, 0) # Меняем оси местами
printTensorInfo(exampleTensorT, "exampleTensorT")
exampleTensorT2 = exampleTensor.mT # Меняем оси местами
printTensorInfo(exampleTensorT2, "exampleTensorT2")



=====exampleTensor=====
tensor:
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26])
shape: torch.Size([27])
dtype: torch.int64
type: torch.LongTensor
dim: 1
=====view=====
tensor:
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23, 24, 25, 26]])
shape: torch.Size([3, 9])
dtype: torch.int64
type: torch.LongTensor
dim: 2
=====view2=====
tensor:
tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])
shape: torch.Size([3, 3, 3])
dtype: torch.int64
type: torch.LongTensor
dim: 3
=====reshape=====
tensor:
tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
    

In [49]:
# squeeze & unsqueeze
test = torch.arange(16).view(4, 2, 2)
printTensorInfo(test, "test")
test = torch.unsqueeze(test, dim=0)
printTensorInfo(test, "test")
test = test.unsqueeze(-1)
printTensorInfo(test, "test")

test = torch.squeeze(test, dim=0)
printTensorInfo(test, "test")
test = torch.squeeze(test)
printTensorInfo(test, "test")

=====test=====
tensor:
tensor([[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]])
shape: torch.Size([4, 2, 2])
dtype: torch.int64
type: torch.LongTensor
dim: 3
=====test=====
tensor:
tensor([[[[ 0,  1],
          [ 2,  3]],

         [[ 4,  5],
          [ 6,  7]],

         [[ 8,  9],
          [10, 11]],

         [[12, 13],
          [14, 15]]]])
shape: torch.Size([1, 4, 2, 2])
dtype: torch.int64
type: torch.LongTensor
dim: 4
=====test=====
tensor:
tensor([[[[[ 0],
           [ 1]],

          [[ 2],
           [ 3]]],


         [[[ 4],
           [ 5]],

          [[ 6],
           [ 7]]],


         [[[ 8],
           [ 9]],

          [[10],
           [11]]],


         [[[12],
           [13]],

          [[14],
           [15]]]]])
shape: torch.Size([1, 4, 2, 2, 1])
dtype: torch.int64
type: torch.LongTensor
dim: 5
=====test=====
tensor:
tensor([[[[ 0],
          [ 1]],

      

In [50]:
# Индексировани и срезы
a = torch.arange(16).view(4, 4)
print(a)
a[0] = torch.arange(16, 12, -1)
print(a)
a[1:] =torch.arange(32, 20, -1).view(3, 4)
print(a)
print(a[1, 1].item())

a += 5
print(a)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])
tensor([[16, 15, 14, 13],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])
tensor([[16, 15, 14, 13],
        [32, 31, 30, 29],
        [28, 27, 26, 25],
        [24, 23, 22, 21]])
31
tensor([[21, 20, 19, 18],
        [37, 36, 35, 34],
        [33, 32, 31, 30],
        [29, 28, 27, 26]])


In [51]:
# Разложение Холецкого
def printMatrixInfo(A, name):
    print(f"{name}:\n{A}")
    print(f"shape: {A.shape}")
    print()

In [52]:
A = torch.tensor([[4.0, 2.0], # Симметричная положительно определённая матрица
                  [2.0, 3.0]])
printMatrixInfo(A, "A")
L = torch.linalg.cholesky(A) # Разложение Холецкого
printMatrixInfo(L, "L (нижнетреугольная)")
A_reconstructed = L @ L.T # Проверка: A = L @ L.T
printMatrixInfo(A_reconstructed, "L @ L.T")

A:
tensor([[4., 2.],
        [2., 3.]])
shape: torch.Size([2, 2])

L (нижнетреугольная):
tensor([[2.0000, 0.0000],
        [1.0000, 1.4142]])
shape: torch.Size([2, 2])

L @ L.T:
tensor([[4.0000, 2.0000],
        [2.0000, 3.0000]])
shape: torch.Size([2, 2])



In [53]:
print("Проверка разложения:\n")
matrices = [
    torch.tensor([[4.0, 2.0], [2.0, 3.0]]),
    torch.tensor([[9.0, 3.0], [3.0, 5.0]])
]
for i, A in enumerate(matrices):
    L = torch.linalg.cholesky(A)
    A_rec = L @ L.T
    print(f"Матрица {i+1}:")
    print("A:")
    print(A)
    print("L @ L.T:")
    print(A_rec)
    diff = torch.max(torch.abs(A - A_rec))
    print(f"Максимальная ошибка: {diff.item()}")

Проверка разложения:

Матрица 1:
A:
tensor([[4., 2.],
        [2., 3.]])
L @ L.T:
tensor([[4.0000, 2.0000],
        [2.0000, 3.0000]])
Максимальная ошибка: 2.384185791015625e-07
Матрица 2:
A:
tensor([[9., 3.],
        [3., 5.]])
L @ L.T:
tensor([[9.0000, 3.0000],
        [3.0000, 5.0000]])
Максимальная ошибка: 2.384185791015625e-07


In [54]:
print("Попытка разложения плохой матрицы:\n")
bad_matrix = torch.tensor([[1.0, 2.0],
                           [2.0, 1.0]])  # не положительно определённая
try:
    L = torch.linalg.cholesky(bad_matrix)
except RuntimeError as e:
    print("Ошибка:")
    print(e)

Попытка разложения плохой матрицы:

Ошибка:
linalg.cholesky: The factorization could not be completed because the input is not positive-definite (the leading minor of order 2 is not positive-definite).


In [55]:
print("Создание корректной матрицы:\n")
X = torch.randn(3, 3) # Любая матрица
A = X @ X.T # Делаем её положительно определённой
printMatrixInfo(A, "A")
L = torch.linalg.cholesky(A)
printMatrixInfo(L, "L")

Создание корректной матрицы:

A:
tensor([[2.2111, 3.1984, 0.2655],
        [3.1984, 6.4792, 0.1093],
        [0.2655, 0.1093, 0.1348]])
shape: torch.Size([3, 3])

L:
tensor([[ 1.4870,  0.0000,  0.0000],
        [ 2.1509,  1.3612,  0.0000],
        [ 0.1785, -0.2018,  0.2494]])
shape: torch.Size([3, 3])



In [56]:
print("Решение системы Ax = b:\n")
A = torch.tensor([[4.0, 2.0], [2.0, 3.0]])
b = torch.tensor([1.0, 1.0])
L = torch.linalg.cholesky(A)
y = torch.linalg.solve(L, b) # Решаем: Ly = b
x = torch.linalg.solve(L.T, y) # Решаем: L^T x = y
print("Решение x:")
print(x)
print("\nПроверка Ax:")
print(A @ x)

Решение системы Ax = b:

Решение x:
tensor([0.1250, 0.2500])

Проверка Ax:
tensor([1., 1.])


In [57]:
# Автоматическое дифференцирование
x = torch.tensor([3.0], requires_grad=True)
y = torch.tensor([1.0], requires_grad=True)

# новая функция
f = x**2 + x * y + y**2

# обратное распространение
f.backward()

# вывод
print("f =", f)

print("x:", x.data, "grad:", x.grad)
print("y:", y.data, "grad:", y.grad)

f = tensor([13.], grad_fn=<AddBackward0>)
x: tensor([3.]) grad: tensor([7.])
y: tensor([1.]) grad: tensor([5.])
