In [1]:
import torch

In [2]:
def printTensorInfo(tensor, title):
    print(f"====={title}=====")
    print(f"tensor:\n{tensor}")
    print(f"shape: {tensor.shape}")
    print(f"dtype: {tensor.dtype}")
    print(f"type: {tensor.type()}")
    print(f"dim: {tensor.dim()}")


In [3]:
# Различные способы создания тензоров
tensorRecommended = torch.Tensor(3, 5, 2)
printTensorInfo(tensorRecommended, "tensorRecommended")
tensorNotRecommended = torch.empty(3, 5, 2)
printTensorInfo(tensorNotRecommended, "tensorNotRecommended")
tensorZeros = torch.zeros(3, 5, 2)
printTensorInfo(tensorZeros, "tensorZeros")
tensorOnes = torch.ones(3, 5, 2)
printTensorInfo(tensorOnes, "tensorOnes")
tensorRand = torch.rand(3, 5, 2)
printTensorInfo(tensorRand, "tensorRand")
tensorSpecificDtype = torch.empty(3, 5, 2, dtype=torch.uint8)
printTensorInfo(tensorSpecificDtype, "tensorSpecificDtype")
tensorClass = torch.IntTensor(3, 5, 2)
printTensorInfo(tensorClass, "tensorClass")

=====tensorRecommended=====
tensor:
tensor([[[2.2163e+12, 1.5793e-42],
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00]]])
shape: torch.Size([3, 5, 2])
dtype: torch.float32
type: torch.FloatTensor
dim: 3
=====tensorNotRecommended=====
tensor:
tensor([[[2.2163e+12, 1.5793e-42],
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+0

In [4]:
# Различные способы создания тензоров с разными значениями
firstTensor = torch.tensor([1])
printTensorInfo(firstTensor, "firstTensor")
secondTensor = torch.tensor([1, 2.0])
printTensorInfo(secondTensor, "secondTensor")
thirdTensor = torch.tensor([[1, 2], [3, 4], [5, 6]])
printTensorInfo(thirdTensor, "thirdTensor")
fourthTensor = torch.tensor([[1, 2], [3, 4], [5, 6]], dtype=torch.float32)
printTensorInfo(fourthTensor, "fourthTensor")

=====firstTensor=====
tensor:
tensor([1])
shape: torch.Size([1])
dtype: torch.int64
type: torch.LongTensor
dim: 1
=====secondTensor=====
tensor:
tensor([1., 2.])
shape: torch.Size([2])
dtype: torch.float32
type: torch.FloatTensor
dim: 1
=====thirdTensor=====
tensor:
tensor([[1, 2],
        [3, 4],
        [5, 6]])
shape: torch.Size([3, 2])
dtype: torch.int64
type: torch.LongTensor
dim: 2
=====fourthTensor=====
tensor:
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
shape: torch.Size([3, 2])
dtype: torch.float32
type: torch.FloatTensor
dim: 2


In [5]:
# Еще способы заполнить тензор
tensorEye = torch.eye(3)
printTensorInfo(tensorEye, "tensorEye")
tensorFull = torch.full((2, 4), 5)
printTensorInfo(tensorFull, "tensorFull")
tensorArange = torch.arange(-5, 0, 2)
printTensorInfo(tensorArange, "tensorArange")
tensorFull.fill_(4) # Только inplace
printTensorInfo(tensorFull, "tensorFull")

=====tensorEye=====
tensor:
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
shape: torch.Size([3, 3])
dtype: torch.float32
type: torch.FloatTensor
dim: 2
=====tensorFull=====
tensor:
tensor([[5, 5, 5, 5],
        [5, 5, 5, 5]])
shape: torch.Size([2, 4])
dtype: torch.int64
type: torch.LongTensor
dim: 2
=====tensorArange=====
tensor:
tensor([-5, -3, -1])
shape: torch.Size([3])
dtype: torch.int64
type: torch.LongTensor
dim: 1
=====tensorFull=====
tensor:
tensor([[4, 4, 4, 4],
        [4, 4, 4, 4]])
shape: torch.Size([2, 4])
dtype: torch.int64
type: torch.LongTensor
dim: 2


In [6]:
# Методы преобразования формы тензоров
exampleTensor = torch.arange(27)
printTensorInfo(exampleTensor, "exampleTensor")
view = exampleTensor.view((3, 9))
printTensorInfo(view, "view")
view2 = exampleTensor.view((3, 3, 3))
printTensorInfo(view2, "view2")
reshape = exampleTensor.reshape(3, 3, 3)
printTensorInfo(reshape, "reshape")

resize = exampleTensor.resize_((2, 3))
exampleTensor[0, 0] = 777
printTensorInfo(resize, "resize")

ravel = exampleTensor.ravel()
printTensorInfo(ravel, "ravel")
exampleTensorT = exampleTensor.permute(1, 0) # Меняем оси местами
printTensorInfo(exampleTensorT, "exampleTensorT")
exampleTensorT2 = exampleTensor.mT # Меняем оси местами
printTensorInfo(exampleTensorT2, "exampleTensorT2")



=====exampleTensor=====
tensor:
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26])
shape: torch.Size([27])
dtype: torch.int64
type: torch.LongTensor
dim: 1
=====view=====
tensor:
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23, 24, 25, 26]])
shape: torch.Size([3, 9])
dtype: torch.int64
type: torch.LongTensor
dim: 2
=====view2=====
tensor:
tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])
shape: torch.Size([3, 3, 3])
dtype: torch.int64
type: torch.LongTensor
dim: 3
=====reshape=====
tensor:
tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
    

In [7]:
# squeeze & unsqueeze
test = torch.arange(16).view(4, 2, 2)
printTensorInfo(test, "test")
test = torch.unsqueeze(test, dim=0)
printTensorInfo(test, "test")
test = test.unsqueeze(-1)
printTensorInfo(test, "test")

test = torch.squeeze(test, dim=0)
printTensorInfo(test, "test")
test = torch.squeeze(test)
printTensorInfo(test, "test")

=====test=====
tensor:
tensor([[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]])
shape: torch.Size([4, 2, 2])
dtype: torch.int64
type: torch.LongTensor
dim: 3
=====test=====
tensor:
tensor([[[[ 0,  1],
          [ 2,  3]],

         [[ 4,  5],
          [ 6,  7]],

         [[ 8,  9],
          [10, 11]],

         [[12, 13],
          [14, 15]]]])
shape: torch.Size([1, 4, 2, 2])
dtype: torch.int64
type: torch.LongTensor
dim: 4
=====test=====
tensor:
tensor([[[[[ 0],
           [ 1]],

          [[ 2],
           [ 3]]],


         [[[ 4],
           [ 5]],

          [[ 6],
           [ 7]]],


         [[[ 8],
           [ 9]],

          [[10],
           [11]]],


         [[[12],
           [13]],

          [[14],
           [15]]]]])
shape: torch.Size([1, 4, 2, 2, 1])
dtype: torch.int64
type: torch.LongTensor
dim: 5
=====test=====
tensor:
tensor([[[[ 0],
          [ 1]],

      

In [8]:
# Индексировани и срезы
a = torch.arange(16).view(4, 4)
print(a)
a[0] = torch.arange(16, 12, -1)
print(a)
a[1:] =torch.arange(32, 20, -1).view(3, 4)
print(a)
print(a[1, 1].item())

a += 5
print(a)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])
tensor([[16, 15, 14, 13],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])
tensor([[16, 15, 14, 13],
        [32, 31, 30, 29],
        [28, 27, 26, 25],
        [24, 23, 22, 21]])
31
tensor([[21, 20, 19, 18],
        [37, 36, 35, 34],
        [33, 32, 31, 30],
        [29, 28, 27, 26]])


In [9]:
# Разложение Холецкого
def printMatrixInfo(A, name):
    print(f"{name}:\n{A}")
    print(f"shape: {A.shape}")
    print()

In [10]:
A = torch.tensor([[4.0, 2.0], # Симметричная положительно определённая матрица
                  [2.0, 3.0]])
printMatrixInfo(A, "A")
L = torch.linalg.cholesky(A) # Разложение Холецкого
printMatrixInfo(L, "L (нижнетреугольная)")
A_reconstructed = L @ L.T # Проверка: A = L @ L.T
printMatrixInfo(A_reconstructed, "L @ L.T")

A:
tensor([[4., 2.],
        [2., 3.]])
shape: torch.Size([2, 2])

L (нижнетреугольная):
tensor([[2.0000, 0.0000],
        [1.0000, 1.4142]])
shape: torch.Size([2, 2])

L @ L.T:
tensor([[4.0000, 2.0000],
        [2.0000, 3.0000]])
shape: torch.Size([2, 2])



In [11]:
print("Проверка разложения:\n")
matrices = [
    torch.tensor([[4.0, 2.0], [2.0, 3.0]]),
    torch.tensor([[9.0, 3.0], [3.0, 5.0]])
]
for i, A in enumerate(matrices):
    L = torch.linalg.cholesky(A)
    A_rec = L @ L.T
    print(f"Матрица {i+1}:")
    print("A:")
    print(A)
    print("L @ L.T:")
    print(A_rec)
    diff = torch.max(torch.abs(A - A_rec))
    print(f"Максимальная ошибка: {diff.item()}")

Проверка разложения:

Матрица 1:
A:
tensor([[4., 2.],
        [2., 3.]])
L @ L.T:
tensor([[4.0000, 2.0000],
        [2.0000, 3.0000]])
Максимальная ошибка: 2.384185791015625e-07
Матрица 2:
A:
tensor([[9., 3.],
        [3., 5.]])
L @ L.T:
tensor([[9.0000, 3.0000],
        [3.0000, 5.0000]])
Максимальная ошибка: 2.384185791015625e-07


In [12]:
print("Попытка разложения плохой матрицы:\n")
bad_matrix = torch.tensor([[1.0, 2.0],
                           [2.0, 1.0]])  # не положительно определённая
try:
    L = torch.linalg.cholesky(bad_matrix)
except RuntimeError as e:
    print("Ошибка:")
    print(e)

Попытка разложения плохой матрицы:

Ошибка:
linalg.cholesky: The factorization could not be completed because the input is not positive-definite (the leading minor of order 2 is not positive-definite).


In [13]:
print("Создание корректной матрицы:\n")
X = torch.randn(3, 3) # Любая матрица
A = X @ X.T # Делаем её положительно определённой
printMatrixInfo(A, "A")
L = torch.linalg.cholesky(A)
printMatrixInfo(L, "L")

Создание корректной матрицы:

A:
tensor([[ 5.4262, -2.4733,  2.3794],
        [-2.4733,  1.3388, -1.2843],
        [ 2.3794, -1.2843,  1.9425]])
shape: torch.Size([3, 3])

L:
tensor([[ 2.3294,  0.0000,  0.0000],
        [-1.0618,  0.4598,  0.0000],
        [ 1.0214, -0.4344,  0.8428]])
shape: torch.Size([3, 3])



In [14]:
print("Решение системы Ax = b:\n")
A = torch.tensor([[4.0, 2.0], [2.0, 3.0]])
b = torch.tensor([1.0, 1.0])
L = torch.linalg.cholesky(A)
y = torch.linalg.solve(L, b) # Решаем: Ly = b
x = torch.linalg.solve(L.T, y) # Решаем: L^T x = y
print("Решение x:")
print(x)
print("\nПроверка Ax:")
print(A @ x)

Решение системы Ax = b:

Решение x:
tensor([0.1250, 0.2500])

Проверка Ax:
tensor([1., 1.])


In [15]:
# Автоматическое дифференцирование
x = torch.tensor([3.0], requires_grad=True)
y = torch.tensor([1.0], requires_grad=True)

# новая функция
f = x**2 + x * y + y**2

# обратное распространение
f.backward()

# вывод
print("f =", f)

print("x:", x.data, "grad:", x.grad)
print("y:", y.data, "grad:", y.grad)

f = tensor([13.], grad_fn=<AddBackward0>)
x: tensor([3.]) grad: tensor([7.])
y: tensor([1.]) grad: tensor([5.])


In [16]:
import os
import json
from PIL import Image

import torch
import torch.utils.data as data
import torchvision.transforms.v2 as tfs
import torch.nn as nn
import torch.optim as optim
from tqdm import tqdm


In [17]:
class AlphabetDataset(data.Dataset):
    def __init__(self, path, train=True, transform=None):
        self.path = os.path.join(path, "train" if train else "test")
        self.transform = transform

        with open(os.path.join(path, "format.json"), "r") as fp:
            self.format = json.load(fp)

        self.length = 0
        self.files = []
        self.targets = torch.eye(26)

        for _dir, _target in self.format.items():
            path = os.path.join(self.path, _dir)
            list_files = os.listdir(path)
            self.length += len(list_files)
            self.files.extend(map(lambda _x: (os.path.join(path, _x), _target), list_files))

    def __getitem__(self, index):
        path_file, target = self.files[index]
        t = self.targets[target]
        img = Image.open(path_file)
        if self.transform:
            img = self.transform(img).ravel().float() / 255.0
        return img, t

    def __len__(self):
        return self.length


In [18]:
class AlphabetNN(nn.Module):
    def __init__(self, input_dim, num_hidden, output_dim):
        super().__init__()
        self.layer1 = nn.Linear(input_dim, num_hidden)
        self.layer2 = nn.Linear(num_hidden, output_dim)

    def forward(self, x):
        x = self.layer1(x)
        x = nn.functional.relu(x)
        x = self.layer2(x)
        return x

In [19]:
model = AlphabetNN(28*28, 32, 26)
to_tensor = tfs.ToImage()
d_train = AlphabetDataset("emnist_letters_folder", transform=to_tensor)
train_data = data.DataLoader(d_train, batch_size=32, shuffle=True)

optimizer = optim.Adam(params=model.parameters(), lr=0.001)
loss_function = nn.CrossEntropyLoss()

epochs = 2
model.train()

AlphabetNN(
  (layer1): Linear(in_features=784, out_features=32, bias=True)
  (layer2): Linear(in_features=32, out_features=26, bias=True)
)

In [20]:
for _e in range(epochs):
    loss_mean = 0 # Среднее значение функции потерь по эпохе
    lm_count = 0 # Текущее количество слагаемых
    train_tqdm = tqdm(train_data, leave=True)
    for x_train, y_train in train_tqdm:
        predict = model(x_train)
        loss = loss_function(predict, y_train)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        lm_count += 1
        loss_mean = 1 / lm_count * loss.item() + (1 - 1 / lm_count) * loss_mean
        train_tqdm.set_description(f"Epoch [{_e + 1}/{epochs}], loss_mean={loss_mean:.3f}")

d_test = AlphabetDataset("emnist_letters_folder", train=False, transform=to_tensor)
test_data = data.DataLoader(d_test, batch_size=500, shuffle=False)
Q = 0

model.eval()

for x_test, y_test in test_data:
    with torch.no_grad():
        p = model(x_test)
        p = torch.argmax(p, dim=1)
        y = torch.argmax(y_test, dim=1)
        Q += torch.sum(p == y).item()

Q /= len(d_test)
print(Q)

Epoch [2/2], loss_mean=0.845: 100%|██████████| 3120/3120 [00:39<00:00, 79.96it/s]


0.7669871794871795
